SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `sg_user` (
  `user_id` VARCHAR(64) NOT NULL COMMENT '系统内部用户唯一ID',
  `nickname` VARCHAR(128) DEFAULT NULL COMMENT '用户显示名称',
  `status` VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '用户状态：active/disabled',
  `last_seen_at` DATETIME(3) DEFAULT NULL COMMENT '最近一次活跃时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (`user_id`),
  KEY `idx_sg_user_status` (`status`),
  KEY `idx_sg_user_last_seen_at` (`last_seen_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户表';

CREATE TABLE IF NOT EXISTS `sg_user_api_key` (
  `api_key_id` VARCHAR(64) NOT NULL COMMENT 'API Key 记录唯一ID',
  `user_id` VARCHAR(64) NOT NULL COMMENT '所属用户ID',
  `provider` VARCHAR(64) NOT NULL DEFAULT 'openai-compatible' COMMENT '模型服务提供方',
  `api_key_hash` CHAR(64) NOT NULL COMMENT 'API Key 哈希值，用于识别用户和去重',
  `api_key_masked` VARCHAR(128) NOT NULL COMMENT '脱敏后的 API Key',
  `api_key_ciphertext` TEXT DEFAULT NULL COMMENT '加密后的 API Key 密文，用于恢复任务时继续调用',
  `status` VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '密钥状态：active/disabled/revoked',
  `is_primary` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否主密钥',
  `last_used_at` DATETIME(3) DEFAULT NULL COMMENT '最近使用时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (`api_key_id`),
  UNIQUE KEY `uk_sg_user_api_key_hash` (`api_key_hash`),
  KEY `idx_sg_user_api_key_user_status` (`user_id`, `status`),
  KEY `idx_sg_user_api_key_last_used_at` (`last_used_at`),
  CONSTRAINT `fk_sg_user_api_key_user_id` FOREIGN KEY (`user_id`) REFERENCES `sg_user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户 API Key 表';

CREATE TABLE IF NOT EXISTS `sg_template` (
  `template_id` VARCHAR(64) NOT NULL COMMENT '模板唯一ID',
  `owner_user_id` VARCHAR(64) DEFAULT NULL COMMENT '模板所属用户ID，内置模板为空',
  `template_name` VARCHAR(255) NOT NULL COMMENT '模板名称',
  `source_type` VARCHAR(32) NOT NULL DEFAULT 'custom' COMMENT '模板来源类型：builtin/custom',
  `source_filename` VARCHAR(255) DEFAULT NULL COMMENT '源文件名',
  `source_ftp_path` VARCHAR(1024) DEFAULT NULL COMMENT '模板源 PPTX 在 FTP 上的路径',
  `imported_svg_dir_ftp_path` VARCHAR(1024) DEFAULT NULL COMMENT '模板导入后的 layered SVG 目录 FTP 路径',
  `imported_svg_flat_dir_ftp_path` VARCHAR(1024) DEFAULT NULL COMMENT '模板导入后的 flat SVG 目录 FTP 路径',
  `assets_ftp_dir_path` VARCHAR(1024) DEFAULT NULL COMMENT '模板资源目录 FTP 路径',
  `manifest_ftp_path` VARCHAR(1024) DEFAULT NULL COMMENT '模板清单文件 FTP 路径',
  `slide_count` INT UNSIGNED DEFAULT NULL COMMENT '模板页数',
  `slide_width_emu` BIGINT DEFAULT NULL COMMENT '页面宽度，单位 EMU',
  `slide_height_emu` BIGINT DEFAULT NULL COMMENT '页面高度，单位 EMU',
  `is_builtin` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否内置模板',
  `status` VARCHAR(32) NOT NULL DEFAULT 'ready' COMMENT '模板状态：importing/ready/failed/disabled',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (`template_id`),
  KEY `idx_sg_template_owner_user_id` (`owner_user_id`),
  KEY `idx_sg_template_is_builtin_status` (`is_builtin`, `status`),
  KEY `idx_sg_template_created_at` (`created_at`),
  CONSTRAINT `fk_sg_template_owner_user_id` FOREIGN KEY (`owner_user_id`) REFERENCES `sg_user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='模板表';

CREATE TABLE IF NOT EXISTS `sg_generation_job` (
  `job_id` VARCHAR(64) NOT NULL COMMENT '任务唯一ID',
  `conversation_id` VARCHAR(64) DEFAULT NULL COMMENT '兼容字段：会话ID，默认等同 job_id',
  `task_id` VARCHAR(64) DEFAULT NULL COMMENT '兼容字段：等同 conversation_id',
  `owner_user_id` VARCHAR(64) NOT NULL COMMENT '任务所属用户ID',
  `user_api_key_id` VARCHAR(64) NOT NULL COMMENT '本次任务使用的用户 API Key 记录ID',
  `template_id` VARCHAR(64) DEFAULT NULL COMMENT '本次任务使用的模板ID',
  `requirement_text` LONGTEXT NOT NULL COMMENT '本次任务的需求全文',
  `request_payload_json` LONGTEXT DEFAULT NULL COMMENT '创建任务时的原始请求 JSON 文本',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '任务状态：pending/running/stopping/stopped/resuming/completed/failed/cancelled',
  `current_stage` VARCHAR(64) NOT NULL DEFAULT 'queued' COMMENT '任务当前阶段',
  `progress` DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '任务进度，范围 0 到 100',
  `stop_requested` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已请求停止',
  `resume_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '任务恢复次数',
  `total_pages` INT UNSIGNED DEFAULT NULL COMMENT '任务总页数',
  `processed_pages` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '已处理页数',
  `completed_pages` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '已完成页数',
  `skipped_pages` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '已跳过页数',
  `failed_pages` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '失败页数',
  `ftp_job_dir` VARCHAR(1024) DEFAULT NULL COMMENT '任务根目录 FTP 路径',
  `ftp_request_path` VARCHAR(1024) DEFAULT NULL COMMENT '任务请求快照文件 FTP 路径',
  `ftp_requirement_path` VARCHAR(1024) DEFAULT NULL COMMENT '需求文件 FTP 路径',
  `ftp_template_snapshot_dir` VARCHAR(1024) DEFAULT NULL COMMENT '任务模板快照目录 FTP 路径',
  `ftp_svg_output_dir` VARCHAR(1024) DEFAULT NULL COMMENT '任务原始 SVG 目录 FTP 路径',
  `ftp_svg_final_dir` VARCHAR(1024) DEFAULT NULL COMMENT '任务最终 SVG 目录 FTP 路径',
  `ftp_validation_report_path` VARCHAR(1024) DEFAULT NULL COMMENT 'SVG 校验报告 FTP 路径',
  `ftp_result_pptx_path` VARCHAR(1024) DEFAULT NULL COMMENT '最终 PPTX FTP 路径',
  `error_code` VARCHAR(64) DEFAULT NULL COMMENT '错误码',
  `error_message` TEXT DEFAULT NULL COMMENT '错误信息',
  `queued_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '入队时间',
  `started_at` DATETIME(3) DEFAULT NULL COMMENT '开始执行时间',
  `stopped_at` DATETIME(3) DEFAULT NULL COMMENT '停止时间',
  `completed_at` DATETIME(3) DEFAULT NULL COMMENT '完成时间',
  `last_heartbeat_at` DATETIME(3) DEFAULT NULL COMMENT '最近一次心跳时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (`job_id`),
  KEY `idx_sg_generation_job_owner_created_at` (`owner_user_id`, `created_at`),
  KEY `idx_sg_generation_job_owner_status_created_at` (`owner_user_id`, `status`, `created_at`),
  KEY `idx_sg_generation_job_status_stage` (`status`, `current_stage`),
  KEY `idx_sg_generation_job_conversation_id` (`conversation_id`),
  KEY `idx_sg_generation_job_task_id` (`task_id`),
  KEY `idx_sg_generation_job_template_id` (`template_id`),
  KEY `idx_sg_generation_job_user_api_key_id` (`user_api_key_id`),
  CONSTRAINT `fk_sg_generation_job_owner_user_id` FOREIGN KEY (`owner_user_id`) REFERENCES `sg_user` (`user_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_sg_generation_job_user_api_key_id` FOREIGN KEY (`user_api_key_id`) REFERENCES `sg_user_api_key` (`api_key_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_sg_generation_job_template_id` FOREIGN KEY (`template_id`) REFERENCES `sg_template` (`template_id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='生成任务主表';

CREATE TABLE IF NOT EXISTS `sg_generation_job_page` (
  `job_id` VARCHAR(64) NOT NULL COMMENT '所属任务ID',
  `page_no` INT UNSIGNED NOT NULL COMMENT '页码，从 1 开始',
  `page_name` VARCHAR(255) DEFAULT NULL COMMENT '页面名称',
  `template_svg_ftp_path` VARCHAR(1024) DEFAULT NULL COMMENT '模板页 SVG 的 FTP 路径',
  `analysis_json_ftp_path` VARCHAR(1024) DEFAULT NULL COMMENT '分页分析 JSON 的 FTP 路径',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '分页状态：pending/running/completed/skipped/failed',
  `should_generate` TINYINT(1) DEFAULT NULL COMMENT '该页是否应保留到最终 PPT',
  `skip_reason` VARCHAR(1000) DEFAULT NULL COMMENT '页面被跳过时的原因',
  `diagram_kind` VARCHAR(64) DEFAULT NULL COMMENT '图形类型，例如 architecture 或 sequence',
  `ftp_generated_svg_path` VARCHAR(1024) DEFAULT NULL COMMENT '原始生成 SVG 的 FTP 路径',
  `ftp_final_svg_path` VARCHAR(1024) DEFAULT NULL COMMENT '最终用于转 PPTX 的 SVG FTP 路径',
  `validation_status` VARCHAR(32) DEFAULT NULL COMMENT '校验状态：pending/passed/failed',
  `validation_message` TEXT DEFAULT NULL COMMENT '校验信息',
  `error_message` TEXT DEFAULT NULL COMMENT '分页失败时的错误信息',
  `started_at` DATETIME(3) DEFAULT NULL COMMENT '开始执行时间',
  `completed_at` DATETIME(3) DEFAULT NULL COMMENT '完成时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (`job_id`, `page_no`),
  KEY `idx_sg_generation_job_page_status` (`status`),
  KEY `idx_sg_generation_job_page_job_status_page_no` (`job_id`, `status`, `page_no`),
  CONSTRAINT `fk_sg_generation_job_page_job_id` FOREIGN KEY (`job_id`) REFERENCES `sg_generation_job` (`job_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='生成任务分页表';

CREATE TABLE IF NOT EXISTS `sg_generation_job_artifact` (
  `artifact_id` VARCHAR(64) NOT NULL COMMENT '产物唯一ID',
  `job_id` VARCHAR(64) NOT NULL COMMENT '所属任务ID',
  `page_no` INT UNSIGNED DEFAULT NULL COMMENT '关联页码，为空表示任务级产物',
  `artifact_type` VARCHAR(64) NOT NULL COMMENT '产物类型，例如 request_json、analysis_json、svg_output、svg_final、result_pptx',
  `ftp_path` VARCHAR(1024) NOT NULL COMMENT '产物在 FTP 上的路径',
  `file_name` VARCHAR(255) DEFAULT NULL COMMENT '文件名',
  `file_ext` VARCHAR(32) DEFAULT NULL COMMENT '文件扩展名',
  `content_type` VARCHAR(128) DEFAULT NULL COMMENT '文件 MIME 类型',
  `file_size_bytes` BIGINT UNSIGNED DEFAULT NULL COMMENT '文件大小，单位字节',
  `checksum_md5` CHAR(32) DEFAULT NULL COMMENT '文件 MD5 摘要',
  `is_final` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否最终产物',
  `status` VARCHAR(32) NOT NULL DEFAULT 'ready' COMMENT '产物状态：ready/deleted/expired',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (`artifact_id`),
  KEY `idx_sg_generation_job_artifact_job_type_created_at` (`job_id`, `artifact_type`, `created_at`),
  KEY `idx_sg_generation_job_artifact_job_page_no` (`job_id`, `page_no`),
  KEY `idx_sg_generation_job_artifact_is_final` (`is_final`),
  CONSTRAINT `fk_sg_generation_job_artifact_job_id` FOREIGN KEY (`job_id`) REFERENCES `sg_generation_job` (`job_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='生成任务产物表';

CREATE TABLE IF NOT EXISTS `sg_generation_job_event` (
  `event_id` VARCHAR(64) NOT NULL COMMENT '事件唯一ID',
  `job_id` VARCHAR(64) NOT NULL COMMENT '所属任务ID',
  `page_no` INT UNSIGNED DEFAULT NULL COMMENT '关联页码，为空表示任务级事件',
  `operator_user_id` VARCHAR(64) DEFAULT NULL COMMENT '事件触发人用户ID',
  `event_type` VARCHAR(64) NOT NULL COMMENT '事件类型，例如 created、status_changed、stop_requested、resumed、page_completed、exported、failed',
  `event_stage` VARCHAR(64) DEFAULT NULL COMMENT '事件发生时所处阶段',
  `event_message` VARCHAR(1000) DEFAULT NULL COMMENT '事件说明',
  `event_detail_json` LONGTEXT DEFAULT NULL COMMENT '事件详情 JSON 文本',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (`event_id`),
  KEY `idx_sg_generation_job_event_job_created_at` (`job_id`, `created_at`),
  KEY `idx_sg_generation_job_event_job_event_type_created_at` (`job_id`, `event_type`, `created_at`),
  KEY `idx_sg_generation_job_event_operator_user_id` (`operator_user_id`),
  CONSTRAINT `fk_sg_generation_job_event_job_id` FOREIGN KEY (`job_id`) REFERENCES `sg_generation_job` (`job_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_sg_generation_job_event_operator_user_id` FOREIGN KEY (`operator_user_id`) REFERENCES `sg_user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='生成任务事件表';

SET FOREIGN_KEY_CHECKS = 1;
